### ISSUE TITLE
Fix Streamlit database issue

### ISSUE THREAD

**Issue by wei2912** [AdvisorySG/mentorship-streamlit#22]
:")

**Comment by Hackin7** [comment]
I've setup a local instance of the repo and tried connecting to the database

Connecting to the database proxy through Streamlit causes the computer to become untrusted

```
Enter password:
ERROR 2026 (HY000): TLS/SSL error: Certificate verification failure: The certificate is NOT trusted.
```

**Comment by wei2912** [comment]
> ```
> Enter password:
> ERROR 2026 (HY000): TLS/SSL error: Certificate verification failure: The certificate is NOT trusted.
> ```

@Hackin7 I don't think the changes address this particular issue, but could you check if you still have any issues with accessing the DB? I'm working on fixing the other issues required to get Streamlit running.

**Comment by wei2912** [comment]
For monitoring user setup, see https://proxysql.com/documentation/ProxySQL-Configuration/#configure-monitoring

**Comment by wei2912** [comment]
Closing since there doesn't seem to be much of an issue currently. Logs look fine too.
